# Script to compile all 99 official ASN from DUK 2026
import json, re

raw_duk = [
    {
        "no": 1,
        "nama": "Dr. ANANG RISGIYANTO S.K.M., M.Kes.",
        "nip_raw": "19750731 200003 1 002",
        "ttl": "METRO, 31-07-1975",
        "pangkat_gol": "PEMBINA UTAMA MADYA",
        "gol": "IV/d",
        "tmt_pangkat": "01-12-2025",
        "jabatan": "KEPALA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "18-09-2025",
        "diklat": "DIKLAT PIM II",
        "tgl_diklat": "17-07-2018",
        "jam_diklat": "887",
        "pendidikan": "DOKTOR - ILMU LINGKUNGAN",
        "tahun_lulus": "2023",
        "jenjang": "DOKTOR",
        "usia": "51 THN 2 BLN",
        "masa_kerja": "24 THN 6 BLN"
    },
    {
        "no": 2,
        "nama": "Ir. IDA SUSANTI S S.T., M.T",
        "nip_raw": "19741009 200604 2 005",
        "ttl": "BANDAR LAMPUNG, 09-10-1974",
        "pangkat_gol": "PEMBINA UTAMA MUDA",
        "gol": "IV/c",
        "tmt_pangkat": "01-07-2026",
        "jabatan": "KEPALA BIDANG PERENCANAAN INFRASTRUKTUR DAN KEWILAYAYAHAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "19-06-2026",
        "diklat": "DIKLAT PIM TK. IV",
        "tgl_diklat": "24-07-2018",
        "jam_diklat": "893",
        "pendidikan": "PASCA SARJANA - TEKNIK",
        "tahun_lulus": "2013",
        "jenjang": "PASCA SARJANA",
        "usia": "51 THN 11 BLN",
        "masa_kerja": "22 THN 0 BLN"
    },
    {
        "no": 3,
        "nama": "MEYDIANDRA EKA PUTRA S.P,MIP",
        "nip_raw": "19730514 199803 1 007",
        "ttl": "TANJUNGKARANG, 14-05-1973",
        "pangkat_gol": "PEMBINA TK. I",
        "gol": "IV/b",
        "tmt_pangkat": "01-04-2016",
        "jabatan": "KEPALA BIDANG PERENCANAAN MAKRO, PENGENDALIAN DAN EVALUASI PEMBANGUNAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "25-04-2025",
        "diklat": "DIKLATPIM III",
        "tgl_diklat": "05-08-2015",
        "jam_diklat": "825",
        "pendidikan": "PASCA SARJANA - MANAJEMEN PEMERINTAHAN",
        "tahun_lulus": "2012",
        "jenjang": "PASCA SARJANA",
        "usia": "53 THN 4 BLN",
        "masa_kerja": "28 THN 7 BLN"
    },
    {
        "no": 4,
        "nama": "Ir. ENDANG WAHYUNI S.T., M.Si.",
        "nip_raw": "19750617 200003 2 001",
        "ttl": "TEGAL REJO, 17-06-1975",
        "pangkat_gol": "PEMBINA TK. I",
        "gol": "IV/b",
        "tmt_pangkat": "01-04-2020",
        "jabatan": "KEPALA BIDANG PERENCANAAN PEREKONOMIAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "19-06-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MASTER OF PLANNING STUDIES",
        "tahun_lulus": "2006",
        "jenjang": "PASCA SARJANA",
        "usia": "51 THN 3 BLN",
        "masa_kerja": "26 THN 6 BLN"
    },
    {
        "no": 5,
        "nama": "DWI PRASETIO S.STP, M.Si",
        "nip_raw": "19780710 199712 1 001",
        "ttl": "TANJUNGKARANG, 10-07-1981",
        "pangkat_gol": "PEMBINA TK. I",
        "gol": "IV/b",
        "tmt_pangkat": "01-04-2023",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "25-05-2026",
        "diklat": "PELATIHAN KEPEMIMPINAN ADMINISTRATOR ANGKATAN IV TAHUN 2024",
        "tgl_diklat": "22-05-2024",
        "jam_diklat": "908",
        "pendidikan": "PASCA SARJANA - MASTER OF SCIENCE",
        "tahun_lulus": "2003",
        "jenjang": "PASCA SARJANA",
        "usia": "45 THN 2 BLN",
        "masa_kerja": "25 THN 5 BLN"
    },
    {
        "no": 6,
        "nama": "ANDI ARAFAT S.T., M.E.",
        "nip_raw": "19740707 200212 1 008",
        "ttl": "JAKARTA, 07-07-1974",
        "pangkat_gol": "PEMBINA TK. I",
        "gol": "IV/b",
        "tmt_pangkat": "01-08-2024",
        "jabatan": "SEKRETARIS PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "25-04-2025",
        "diklat": "SUDAH DIKLAT PIM IV",
        "tgl_diklat": "23-04-2013",
        "jam_diklat": "310",
        "pendidikan": "EKONOMI PEMBANGUNAN & PERENCANAAN",
        "tahun_lulus": "2007",
        "jenjang": "PASCA SARJANA",
        "usia": "52 THN 2 BLN",
        "masa_kerja": "23 THN 9 BLN"
    },
    {
        "no": 7,
        "nama": "AWLIYANTI S.Si,Apt",
        "nip_raw": "19760812 200312 2 001",
        "ttl": "JAKARTA, 12-08-1976",
        "pangkat_gol": "PEMBINA TK. I",
        "gol": "IV/b",
        "tmt_pangkat": "01-08-2024",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH",
        "tmt_jabatan": "08-06-2021",
        "diklat": "PENDIDIKAN DAN PELATIHAN PRAJABATAN GOL.III",
        "tgl_diklat": "10-10-2004",
        "jam_diklat": "135",
        "pendidikan": "FARMASI",
        "tahun_lulus": "2002",
        "jenjang": "PASCA SARJANA",
        "usia": "50 THN 1 BLN",
        "masa_kerja": "22 THN 9 BLN"
    },
    {
        "no": 8,
        "nama": "KAIZAN SP.,M.Si",
        "nip_raw": "19730323 200212 1 011",
        "ttl": "KOTABUMI, 23-03-1973",
        "pangkat_gol": "PEMBINA TK. I",
        "gol": "IV/b",
        "tmt_pangkat": "01-10-2024",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH",
        "tmt_jabatan": "08-06-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MASTER OF SCIENCE",
        "tahun_lulus": "2014",
        "jenjang": "PASCA SARJANA",
        "usia": "53 THN 6 BLN",
        "masa_kerja": "21 THN 5 BLN"
    },
    {
        "no": 9,
        "nama": "DECKY FERDIANSYAH S.Si.Apt., M.S.P",
        "nip_raw": "19790819 200501 1 008",
        "ttl": "KOTABUMI, 19-08-1979",
        "pangkat_gol": "PEMBINA TK. I",
        "gol": "IV/b",
        "tmt_pangkat": "01-10-2024",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN DAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "08-06-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER STUDI PEMBANGUNAN",
        "tahun_lulus": "2019",
        "jenjang": "PASCA SARJANA",
        "usia": "47 THN 1 BLN",
        "masa_kerja": "21 THN 8 BLN"
    },
    {
        "no": 10,
        "nama": "MHD YUSUF NASUTION S.Sos, M.Si",
        "nip_raw": "19671122 198903 1 003",
        "ttl": "MEDAN, 22-11-1967",
        "pangkat_gol": "PEMBINA TK. I",
        "gol": "IV/b",
        "tmt_pangkat": "01-06-2025",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH",
        "tmt_jabatan": "08-06-2021",
        "diklat": "ADUM/SEPADA/PIM IV",
        "tgl_diklat": "20-04-2007",
        "jam_diklat": "302",
        "pendidikan": "KEBIJAKAN ADMINISTRASI PUBLIK",
        "tahun_lulus": "2004",
        "jenjang": "PASCA SARJANA",
        "usia": "58 THN 10 BLN",
        "masa_kerja": "32 THN 6 BLN"
    },
    {
        "no": 11,
        "nama": "PRAYUDI ARIBOWO SSTP",
        "nip_raw": "19760608 199511 1 001",
        "ttl": "TANJUNGKARANG, 08-06-1976",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-04-2014",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2021",
        "diklat": "ADUM/SEPADA/PIM IV",
        "tgl_diklat": "12-08-1999",
        "jam_diklat": "250",
        "pendidikan": "DIPLOMA IV - ILMU PEMERINTAHAN",
        "tahun_lulus": "1999",
        "jenjang": "DIPLOMA IV",
        "usia": "50 THN 3 BLN",
        "masa_kerja": "26 THN 11 BLN"
    },
    {
        "no": 12,
        "nama": "MERYLIA S.T., M.T., M.Sc",
        "nip_raw": "19800316 200212 2 004",
        "ttl": "KOTABUMI, 16-03-1980",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-04-2019",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "02-06-2026",
        "diklat": "DIKLAT JABATAN PNS",
        "tgl_diklat": "21-10-2003",
        "jam_diklat": "135",
        "pendidikan": "PASCA SARJANA - MASTER OF SCIENCE",
        "tahun_lulus": "2007",
        "jenjang": "PASCA SARJANA",
        "usia": "46 THN 6 BLN",
        "masa_kerja": "23 THN 9 BLN"
    },
    {
        "no": 13,
        "nama": "WAHYU HIDAYAT S.T., M.M.",
        "nip_raw": "19760607 200604 1 011",
        "ttl": "TANJUNG KARANG, 07-06-1976",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-04-2020",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2011",
        "jenjang": "PASCA SARJANA",
        "usia": "50 THN 3 BLN",
        "masa_kerja": "23 THN 5 BLN"
    },
    {
        "no": 14,
        "nama": "MUHAMMAD FAUZI , S.T., M.E.",
        "nip_raw": "19750921 200501 1 004",
        "ttl": "KOTA GAJAH, 21-09-1975",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-04-2021",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "06-03-2026",
        "diklat": "DIKLAT PRAJABATAN GOL. III",
        "tgl_diklat": "04-07-2005",
        "jam_diklat": "135",
        "pendidikan": "PASCA SARJANA - EKONOMI",
        "tahun_lulus": "2011",
        "jenjang": "PASCA SARJANA",
        "usia": "51 THN 0 BLN",
        "masa_kerja": "24 THN 3 BLN"
    },
    {
        "no": 15,
        "nama": "CATUR MAKHMUDI S.Hut., M.I.L",
        "nip_raw": "19760509 200604 1 007",
        "ttl": "GOMBONG KEBUMEN, 09-05-1976",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-04-2022",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "06-03-2026",
        "diklat": "PENDIDIKAN DAN PELATIHAN PRAJABATAN CPNS",
        "tgl_diklat": "07-09-2006",
        "jam_diklat": "135",
        "pendidikan": "PASCA SARJANA - ILMU LINGKUNGAN",
        "tahun_lulus": "2011",
        "jenjang": "PASCA SARJANA",
        "usia": "50 THN 4 BLN",
        "masa_kerja": "20 THN 5 BLN"
    },
    {
        "no": 16,
        "nama": "CIK MARYA S.E.,M.M.",
        "nip_raw": "19691026 199203 2 002",
        "ttl": "LAMPUNG BARAT, 26-10-1969",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-04-2023",
        "jabatan": "KEPALA SUB BAGIAN UMUM DAN KEPEGAWAIAN PADA SEKRETARIAT BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "11-10-2024",
        "diklat": "DIKLAT PRAJABATAN GOL II",
        "tgl_diklat": "27-09-1993",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2022",
        "jenjang": "PASCA SARJANA",
        "usia": "56 THN 11 BLN",
        "masa_kerja": "29 THN 7 BLN"
    },
    {
        "no": 17,
        "nama": "ELIYATI S.Kom,M.M",
        "nip_raw": "19870201 200902 2 004",
        "ttl": "BUMI AGUNG, 01-02-1987",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-04-2023",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "22-01-2026",
        "diklat": "PRAJABATAN GOL III",
        "tgl_diklat": "04-11-2010",
        "jam_diklat": "135",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2011",
        "jenjang": "PASCA SARJANA",
        "usia": "39 THN 7 BLN",
        "masa_kerja": "17 THN 9 BLN"
    },
    {
        "no": 18,
        "nama": "MUHAMMAD RIDUWAN PASRA S.E., M.B.A.",
        "nip_raw": "19821024 201001 1 012",
        "ttl": "BANDAR LAMPUNG, 24-10-1982",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-06-2024",
        "jabatan": "KEPALA SEKSI DATA GEOSPASIAL PADA UPTD PUSAT DATA DAN INFORMASI PEMBANGUNAN DAERAH BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "08-04-2020",
        "diklat": "DIKLAT PIM TK. IV",
        "tgl_diklat": "28-08-2014",
        "jam_diklat": "867",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2008",
        "jenjang": "PASCA SARJANA",
        "usia": "43 THN 11 BLN",
        "masa_kerja": "17 THN 1 BLN"
    },
    {
        "no": 19,
        "nama": "YULIYANA S.T., M.M.",
        "nip_raw": "19781230 200903 2 002",
        "ttl": "TANJUNGKARANG, 30-12-1978",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-10-2024",
        "jabatan": "KEPALA SUB BAGIAN TATA USAHA PADA UPTD PUSAT DATA DAN INFORMASI PEMBANGUNAN DAERAH BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "02-02-2021",
        "diklat": "PRAJABATAN",
        "tgl_diklat": "21-09-2010",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2012",
        "jenjang": "PASCA SARJANA",
        "usia": "47 THN 9 BLN",
        "masa_kerja": "23 THN 11 BLN"
    },
    {
        "no": 20,
        "nama": "YASIR WIJAYA S.Si.,M.Si",
        "nip_raw": "19840505 201003 1 002",
        "ttl": "SEMULI JAYA, 05-05-1984",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-10-2025",
        "jabatan": "KEPALA UPTD PUSAT DATA DAN INFORMASI PEMBANGUNAN DAERAH PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "03-06-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - ILMU LINGKUNGAN",
        "tahun_lulus": "2012",
        "jenjang": "PASCA SARJANA",
        "usia": "42 THN 4 BLN",
        "masa_kerja": "16 THN 6 BLN"
    },
    {
        "no": 21,
        "nama": "ANDRI BUDHI DHARMA S.H",
        "nip_raw": "19840820 201001 1 013",
        "ttl": "BANDAR LAMPUNG, 20-08-1984",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-06-2026",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "06-03-2026",
        "diklat": "PIM IV",
        "tgl_diklat": "26-08-2014",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - HUKUM",
        "tahun_lulus": "2006",
        "jenjang": "SARJANA",
        "usia": "42 THN 1 BLN",
        "masa_kerja": "17 THN 8 BLN"
    },
    {
        "no": 22,
        "nama": "RATNI PUSPA DEWI S.T.",
        "nip_raw": "19690713 199703 2 001",
        "ttl": "TANJUNGKARANG, 13-07-1969",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-08-2026",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "02-06-2026",
        "diklat": "ADUM/SEPADA/PIM IV",
        "tgl_diklat": "30-10-1999",
        "jam_diklat": "250",
        "pendidikan": "SARJANA - TEKHNOLOGI GEOLOGI",
        "tahun_lulus": "1995",
        "jenjang": "SARJANA",
        "usia": "57 THN 2 BLN",
        "masa_kerja": "29 THN 6 BLN"
    },
    {
        "no": 23,
        "nama": "LOLA AFRYANA SYA`YAN S.E., M.M",
        "nip_raw": "19770426 200902 2 001",
        "ttl": "GISTING, 26-04-1977",
        "pangkat_gol": "PEMBINA",
        "gol": "IV/a",
        "tmt_pangkat": "01-08-2026",
        "jabatan": "PERENCANA AHLI MADYA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "02-06-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MANAJEMEN",
        "tahun_lulus": "2011",
        "jenjang": "PASCA SARJANA",
        "usia": "49 THN 5 BLN",
        "masa_kerja": "20 THN 1 BLN"
    },
    {
        "no": 24,
        "nama": "AHMAD AMRULLAH S.T.",
        "nip_raw": "19710823 200212 1 002",
        "ttl": "TANJUNGKARANG, 23-08-1971",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2017",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "DIKLAT KEPEMIMPINAN TK IV (DIKLATPIM TK IV)",
        "tgl_diklat": "25-05-2005",
        "jam_diklat": "0",
        "pendidikan": "SARJANA - TEKNIK SIPIL",
        "tahun_lulus": "1999",
        "jenjang": "SARJANA",
        "usia": "55 THN 1 BLN",
        "masa_kerja": "23 THN 9 BLN"
    },
    {
        "no": 25,
        "nama": "NAOMI SETYAWATI S.E",
        "nip_raw": "19771014 200312 2 005",
        "ttl": "TANJUNGKARANG, 14-10-1977",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2017",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - EKONOMI",
        "tahun_lulus": "2001",
        "jenjang": "SARJANA",
        "usia": "48 THN 11 BLN",
        "masa_kerja": "22 THN 9 BLN"
    },
    {
        "no": 26,
        "nama": "AMRULLAH KURNIAWAN S.E.",
        "nip_raw": "19720711 200604 1 011",
        "ttl": "TANJUNG KARANG, 11-07-1972",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2017",
        "jabatan": "PENGOLAH DATA DAN INFORMASI PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - EKONOMI",
        "tahun_lulus": "1999",
        "jenjang": "SARJANA",
        "usia": "54 THN 2 BLN",
        "masa_kerja": "24 THN 5 BLN"
    },
    {
        "no": 27,
        "nama": "YUNITA DEWI S.P",
        "nip_raw": "19800613 200501 2 006",
        "ttl": "TANJUNG KARANG, 13-06-1980",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2018",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBAGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "03-06-2020",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - PERTANIAN",
        "tahun_lulus": "2004",
        "jenjang": "SARJANA",
        "usia": "46 THN 3 BLN",
        "masa_kerja": "21 THN 8 BLN"
    },
    {
        "no": 28,
        "nama": "RAHMIYANITA HAKIM S.H., M.H",
        "nip_raw": "19880108 200902 2 003",
        "ttl": "BANDAR LAMPUNG, 08-01-1988",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-10-2018",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH",
        "tmt_jabatan": "08-06-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - HUKUM",
        "tahun_lulus": "2011",
        "jenjang": "PASCA SARJANA",
        "usia": "38 THN 8 BLN",
        "masa_kerja": "17 THN 7 BLN"
    },
    {
        "no": 29,
        "nama": "Ir. YULIUS ARI WIKARTA S.Hut.",
        "nip_raw": "19851120 201001 1 009",
        "ttl": "GISTING, 20-11-1985",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-10-2019",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "22-01-2026",
        "diklat": "DIKLATPIM IV",
        "tgl_diklat": "09-09-2015",
        "jam_diklat": "867",
        "pendidikan": "SARJANA - MANAJEMEN",
        "tahun_lulus": "2008",
        "jenjang": "SARJANA",
        "usia": "40 THN 10 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 30,
        "nama": "RATIH WIDIYANTI SE, MM",
        "nip_raw": "19821229 200212 2 002",
        "ttl": "KAYU AGUNG, 29-12-1982",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2020",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "14-06-2022",
        "diklat": "PIM IV",
        "tgl_diklat": "15-03-2013",
        "jam_diklat": "310",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2013",
        "jenjang": "PASCA SARJANA",
        "usia": "43 THN 9 BLN",
        "masa_kerja": "18 THN 9 BLN"
    },
    {
        "no": 31,
        "nama": "TITA NOVITA S.K.M., M.K.M.",
        "nip_raw": "19791101 200312 2 007",
        "ttl": "Teluk Betung, 01-11-1979",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2021",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PRENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "09-11-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER KESEHATAN MASYARAKAT",
        "tahun_lulus": "2013",
        "jenjang": "PASCA SARJANA",
        "usia": "46 THN 10 BLN",
        "masa_kerja": "20 THN 9 BLN"
    },
    {
        "no": 32,
        "nama": "ERA JAYANTI S.STP,MM",
        "nip_raw": "19860329 200602 2 002",
        "ttl": "TANJUNGKARANG, 29-03-1986",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2021",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2021",
        "diklat": "PRAJABATAN",
        "tgl_diklat": "12-02-2007",
        "jam_diklat": "90",
        "pendidikan": "PASCA SARJANA - MANAJEMEN",
        "tahun_lulus": "2011",
        "jenjang": "PASCA SARJANA",
        "usia": "40 THN 6 BLN",
        "masa_kerja": "17 THN 5 BLN"
    },
    {
        "no": 33,
        "nama": "LOKOSMI SABA OCDITA ST.,M.T",
        "nip_raw": "19780517 200902 2 001",
        "ttl": "Pringsewu, 17-05-1978",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2021",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PRENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "09-11-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - TEKNIK SIPIL",
        "tahun_lulus": "2022",
        "jenjang": "PASCA SARJANA",
        "usia": "48 THN 4 BLN",
        "masa_kerja": "17 THN 7 BLN"
    },
    {
        "no": 34,
        "nama": "EVA MEFRIDAWATI SE., MM",
        "nip_raw": "19850527 201001 2 007",
        "ttl": "KOTABUMI, 27-05-1985",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2021",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "26-06-2023",
        "diklat": "DIKLAT PRAJABATAN GOL. III",
        "tgl_diklat": "18-05-2011",
        "jam_diklat": "135",
        "pendidikan": "PASCA SARJANA - MANAJEMEN",
        "tahun_lulus": "2010",
        "jenjang": "PASCA SARJANA",
        "usia": "41 THN 4 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 35,
        "nama": "SYAHRIL JAYASAPUTRA S.T.",
        "nip_raw": "19710722 200903 1 001",
        "ttl": "BANDAR LAMPUNG, 22-07-1971",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2021",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "PRAJABATAN",
        "tgl_diklat": "14-06-2010",
        "jam_diklat": "216",
        "pendidikan": "SARJANA - TEKNIK",
        "tahun_lulus": "2001",
        "jenjang": "SARJANA",
        "usia": "55 THN 2 BLN",
        "masa_kerja": "22 THN 11 BLN"
    },
    {
        "no": 36,
        "nama": "MIRAYA DARDANILA S.IP., M.T",
        "nip_raw": "19880910 200701 2 002",
        "ttl": "KOTABUMI, 10-09-1988",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-10-2021",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "18-10-2022",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - TEKNIK",
        "tahun_lulus": "2016",
        "jenjang": "PASCA SARJANA",
        "usia": "38 THN 0 BLN",
        "masa_kerja": "16 THN 11 BLN"
    },
    {
        "no": 37,
        "nama": "RATIH AULIA RAHMAYANTI S.Si.,M.Sc",
        "nip_raw": "19841103 201101 2 009",
        "ttl": "BANDAR LAMPUNG, 03-11-1984",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-10-2021",
        "jabatan": "SURVEYOR PEMETAAN AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "14-06-2022",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - ILMU LINGKUNGAN",
        "tahun_lulus": "2009",
        "jenjang": "PASCA SARJANA",
        "usia": "41 THN 10 BLN",
        "masa_kerja": "15 THN 8 BLN"
    },
    {
        "no": 38,
        "nama": "SILFA GUSMAN SE., M.M.",
        "nip_raw": "19820825 201001 1 017",
        "ttl": "XXXX, 25-08-1982",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2022",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MANAJEMEN",
        "tahun_lulus": "2024",
        "jenjang": "PASCA SARJANA",
        "usia": "44 THN 1 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 39,
        "nama": "SINTHA AGUSTIANTI S.H., M.H.",
        "nip_raw": "19800809 201001 2 012",
        "ttl": "TANJUNG KARANG, 09-08-1980",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2022",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH",
        "tmt_jabatan": "14-06-2022",
        "diklat": "PRAJAB GOL III",
        "tgl_diklat": "26-04-2011",
        "jam_diklat": "135",
        "pendidikan": "PASCA SARJANA - HUKUM",
        "tahun_lulus": "2013",
        "jenjang": "PASCA SARJANA",
        "usia": "46 THN 1 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 40,
        "nama": "YENY FITRIANI S.E., M.Si",
        "nip_raw": "19810610 201001 2 019",
        "ttl": "TANJUNG KARANG, 10-06-1981",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2022",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - ILMU ADMINISTRASI",
        "tahun_lulus": "2016",
        "jenjang": "PASCA SARJANA",
        "usia": "45 THN 3 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 41,
        "nama": "AUDI KURNIAWAN ST., MM",
        "nip_raw": "19820812 201001 1 012",
        "ttl": "JAKARTA, 12-08-1982",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2022",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MANAJEMEN",
        "tahun_lulus": "2014",
        "jenjang": "PASCA SARJANA",
        "usia": "44 THN 1 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 42,
        "nama": "RIYA SONETA S.KOM.,MM",
        "nip_raw": "19840617 201001 2 005",
        "ttl": "NEGARA BATIN, 17-06-1984",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2022",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2021",
        "diklat": "PRAJABATAN",
        "tgl_diklat": "14-06-2011",
        "jam_diklat": "135",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2022",
        "jenjang": "PASCA SARJANA",
        "usia": "42 THN 3 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 43,
        "nama": "HARYO WICAKSONO SE",
        "nip_raw": "19760307 201001 1 007",
        "ttl": "LAMPUNG TIMUR, 07-03-1976",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2022",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - EKONOMI",
        "tahun_lulus": "2003",
        "jenjang": "SARJANA",
        "usia": "50 THN 6 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 44,
        "nama": "YUDI ASTARI SE",
        "nip_raw": "19760626 201001 1 010",
        "ttl": "TANJUNG KARANG, 26-06-1976",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2022",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - MANAJEMEN",
        "tahun_lulus": "2000",
        "jenjang": "SARJANA",
        "usia": "50 THN 3 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 45,
        "nama": "ANDRE VICTOR MUCHSIN S.E., M.M",
        "nip_raw": "19760307 201001 1 008",
        "ttl": "BANDAR LAMPUNG, 07-03-1976",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-10-2022",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2021",
        "jenjang": "PASCA SARJANA",
        "usia": "50 THN 6 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 46,
        "nama": "NORMA YUNITA S.IP, M.M.",
        "nip_raw": "19780612 199803 2 003",
        "ttl": "TANJUNG AGUNG, 12-06-1978",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2023",
        "jabatan": "KEPALA SUB BAGIAN KEUANGAN DAN ASET PADA SEKRETARIAT BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "11-10-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - ILMU PEMERINTAHAN",
        "tahun_lulus": "2010",
        "jenjang": "SARJANA",
        "usia": "48 THN 3 BLN",
        "masa_kerja": "23 THN 7 BLN"
    },
    {
        "no": 47,
        "nama": "MUHAMAD AIRLANGGA SE",
        "nip_raw": "19751130 201101 1 002",
        "ttl": "PALEMBANG, 30-11-1975",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2023",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "PRAJABATAN GOL III",
        "tgl_diklat": "15-06-2011",
        "jam_diklat": "135",
        "pendidikan": "EKONOMI AKUNTANSI",
        "tahun_lulus": "1998",
        "jenjang": "SARJANA",
        "usia": "50 THN 10 BLN",
        "masa_kerja": "15 THN 11 BLN"
    },
    {
        "no": 48,
        "nama": "Dr. SUPENO S.Pd.Kor.,M.Pd.",
        "nip_raw": "19850226 201101 1 002",
        "ttl": "TELUK BETUNG, 26-02-1985",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-10-2023",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "21-05-2025",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "DOKTOR - PENDIDIKAN OLAHRAGA",
        "tahun_lulus": "2016",
        "jenjang": "DOKTOR",
        "usia": "41 THN 7 BLN",
        "masa_kerja": "15 THN 8 BLN"
    },
    {
        "no": 49,
        "nama": "NELLY ASTUTI S.E., M.M",
        "nip_raw": "19800927 201101 2 002",
        "ttl": "TANJUNG KARANG, 27-09-1980",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-12-2024",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH",
        "tmt_jabatan": "08-06-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2013",
        "jenjang": "PASCA SARJANA",
        "usia": "46 THN 0 BLN",
        "masa_kerja": "15 THN 8 BLN"
    },
    {
        "no": 50,
        "nama": "M. ROBY SATRIA PRATAMA S.T., M.SI.",
        "nip_raw": "19860113 201101 1 009",
        "ttl": "BANDAR LAMPUNG, 13-01-1986",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-12-2024",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - ILMU ADMINISTRASI",
        "tahun_lulus": "2022",
        "jenjang": "PASCA SARJANA",
        "usia": "40 THN 8 BLN",
        "masa_kerja": "13 THN 8 BLN"
    },
    {
        "no": 51,
        "nama": "DEDY APRIZAL S.TP.,M.Si",
        "nip_raw": "19841230 201503 1 001",
        "ttl": "KALIBALANGAN, 30-12-1984",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-12-2024",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "PRAJABATAN",
        "tgl_diklat": "12-05-2016",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER SAINS",
        "tahun_lulus": "2011",
        "jenjang": "PASCA SARJANA",
        "usia": "41 THN 9 BLN",
        "masa_kerja": "11 THN 6 BLN"
    },
    {
        "no": 52,
        "nama": "SYAIFUL RAHMAT S.E., M.I.D.S,.M.E.",
        "nip_raw": "19811225 201001 1 022",
        "ttl": "TANJUNG KARANG, 25-12-1981",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-02-2025",
        "jabatan": "KEPALA SEKSI DATA STATISTIK PADA UPTD PUSAT DATA DAN INFORMASI PEMBANGUNAN DAERAH BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "02-05-2025",
        "diklat": "PRAJABATAN",
        "tgl_diklat": "24-06-2011",
        "jam_diklat": "135",
        "pendidikan": "PASCA SARJANA - MAGISTER EKONOMI",
        "tahun_lulus": "2017",
        "jenjang": "PASCA SARJANA",
        "usia": "44 THN 9 BLN",
        "masa_kerja": "15 THN 7 BLN"
    },
    {
        "no": 53,
        "nama": "DIAN RACHMAWATY SP., MM.",
        "nip_raw": "19791025 201001 2 018",
        "ttl": "TANJUNG KARANG, 25-10-1979",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-02-2025",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "09-11-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2021",
        "jenjang": "PASCA SARJANA",
        "usia": "46 THN 11 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 54,
        "nama": "DIELLA DWI SARTIKA ST., MT",
        "nip_raw": "19860329 201101 2 007",
        "ttl": "BANDUNG, 29-03-1986",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-02-2025",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "09-11-2021",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - TEKNIK PEMBANGUNAN WILAYAH DAN KOTA",
        "tahun_lulus": "2016",
        "jenjang": "PASCA SARJANA",
        "usia": "40 THN 6 BLN",
        "masa_kerja": "15 THN 8 BLN"
    },
    {
        "no": 55,
        "nama": "HEFRIZAL GHAZALI S.STP., M.M",
        "nip_raw": "19880809 201206 1 001",
        "ttl": "METRO, 09-08-1988",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-02-2025",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "DIKLATPIM TK. IV",
        "tgl_diklat": "01-10-2013",
        "jam_diklat": "285",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2015",
        "jenjang": "PASCA SARJANA",
        "usia": "38 THN 1 BLN",
        "masa_kerja": "12 THN 7 BLN"
    },
    {
        "no": 56,
        "nama": "RIKA YUNIATI S.E, M.M",
        "nip_raw": "19820625 201101 2 007",
        "ttl": "-, 25-06-1982",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2025",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER MANAJEMEN",
        "tahun_lulus": "2015",
        "jenjang": "PASCA SARJANA",
        "usia": "44 THN 3 BLN",
        "masa_kerja": "17 THN 8 BLN"
    },
    {
        "no": 57,
        "nama": "ANDYTIA PRATIWI S.T.M.T",
        "nip_raw": "19870428 201101 2 011",
        "ttl": "TANJUNG KARANG, 28-04-1987",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2025",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "PRAJABATAN",
        "tgl_diklat": "21-01-2012",
        "jam_diklat": "216",
        "pendidikan": "PASCA SARJANA - TEKNIK",
        "tahun_lulus": "2014",
        "jenjang": "PASCA SARJANA",
        "usia": "39 THN 5 BLN",
        "masa_kerja": "15 THN 8 BLN"
    },
    {
        "no": 58,
        "nama": "ARIESCO OKTAVIAN SE",
        "nip_raw": "19761031 201212 1 001",
        "ttl": "BANDAR LAMPUNG, 31-10-1976",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2025",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "26-06-2023",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "MANAJEMEN",
        "tahun_lulus": "2004",
        "jenjang": "SARJANA",
        "usia": "49 THN 11 BLN",
        "masa_kerja": "21 THN 8 BLN"
    },
    {
        "no": 59,
        "nama": "RADIUS PRAWIRA NEGARA S.ST",
        "nip_raw": "19780831 200501 1 006",
        "ttl": "BALAI KENCANA, 31-08-1978",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-06-2025",
        "jabatan": "KEPALA BIDANG PERENCANAAN PEMERINTAHAN DAN PEMBANGUNAN MANUSIA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "14-08-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - SAINS",
        "tahun_lulus": "2013",
        "jenjang": "SARJANA",
        "usia": "48 THN 1 BLN",
        "masa_kerja": "19 THN 8 BLN"
    },
    {
        "no": 60,
        "nama": "KORNELLA RESTIANTI SKM., M.Ling",
        "nip_raw": "19810125 200804 2 002",
        "ttl": "TANJUNG KARANG, 25-01-1981",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-01-2026",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER LINGKUNGAN",
        "tahun_lulus": "2020",
        "jenjang": "PASCA SARJANA",
        "usia": "45 THN 8 BLN",
        "masa_kerja": "16 THN 5 BLN"
    },
    {
        "no": 61,
        "nama": "REVARIO OKTANO S.Si.",
        "nip_raw": "19831009 201001 1 010",
        "ttl": "PARDASUKA, 09-10-1983",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-03-2026",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "09-11-2021",
        "diklat": "DIKLAT PRAJABATAN",
        "tgl_diklat": "15-06-2011",
        "jam_diklat": "135",
        "pendidikan": "SARJANA - STATISTIK",
        "tahun_lulus": "2006",
        "jenjang": "SARJANA",
        "usia": "42 THN 11 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 62,
        "nama": "DIAH RAHMAWATI SE",
        "nip_raw": "19850919 201402 2 001",
        "ttl": "METRO, 19-09-1985",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-03-2026",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "PRAJABATAN",
        "tgl_diklat": "27-01-2015",
        "jam_diklat": "263",
        "pendidikan": "SARJANA - AKUNTANSI",
        "tahun_lulus": "2011",
        "jenjang": "SARJANA",
        "usia": "41 THN 0 BLN",
        "masa_kerja": "12 THN 7 BLN"
    },
    {
        "no": 63,
        "nama": "RIMA BUDI ARISTA S.E.",
        "nip_raw": "19920719 201503 2 002",
        "ttl": "LAMPUNG TIMUR, 19-07-1992",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-03-2026",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - AKUNTANSI",
        "tahun_lulus": "2014",
        "jenjang": "SARJANA",
        "usia": "34 THN 2 BLN",
        "masa_kerja": "11 THN 7 BLN"
    },
    {
        "no": 64,
        "nama": "RIA LIZA NOVITA TH S.E.",
        "nip_raw": "19871113 201101 2 010",
        "ttl": "BANDAR LAMPUNG, 13-11-1987",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2026",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "26-06-2023",
        "diklat": "PRAJABATAN GOLONGAN DUA",
        "tgl_diklat": "04-05-2011",
        "jam_diklat": "90",
        "pendidikan": "SARJANA - AKUNTANSI",
        "tahun_lulus": "2014",
        "jenjang": "SARJANA",
        "usia": "38 THN 10 BLN",
        "masa_kerja": "13 THN 8 BLN"
    },
    {
        "no": 65,
        "nama": "DESSY ANGGRAHITA SH",
        "nip_raw": "19890709 201402 2 008",
        "ttl": "SLEMAN YOGYAKARTA, 09-07-1989",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-04-2026",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - HUKUM",
        "tahun_lulus": "2011",
        "jenjang": "SARJANA",
        "usia": "37 THN 2 BLN",
        "masa_kerja": "12 THN 7 BLN"
    },
    {
        "no": 66,
        "nama": "PURIATMA NUR UTOMO S.STP.",
        "nip_raw": "19921120 201406 1 001",
        "ttl": "BANDAR LAMPUNG, 20-11-1992",
        "pangkat_gol": "PENATA TK. I",
        "gol": "III/d",
        "tmt_pangkat": "01-05-2026",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "DIPLOMA IV - SEKOLAH TINGGI PEMERINTAHAN DALAM NEGERI",
        "tahun_lulus": "2014",
        "jenjang": "DIPLOMA IV",
        "usia": "33 THN 10 BLN",
        "masa_kerja": "12 THN 7 BLN"
    },
    {
        "no": 67,
        "nama": "AHMAD KOSASIH A.Md.",
        "nip_raw": "19740814 200112 1 001",
        "ttl": "JAKARTA, 14-08-1974",
        "pangkat_gol": "PENATA",
        "gol": "III/c",
        "tmt_pangkat": "01-04-2019",
        "jabatan": "PENGOLAH DATA DAN INFORMASI PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "DIPLOMA III - AKUNTANSI",
        "tahun_lulus": "1996",
        "jenjang": "DIPLOMA III",
        "usia": "52 THN 1 BLN",
        "masa_kerja": "22 THN 9 BLN"
    },
    {
        "no": 68,
        "nama": "SITI MASITOH S.E.",
        "nip_raw": "19840706 201503 2 001",
        "ttl": "BANDAR LAMPUNG, 06-07-1984",
        "pangkat_gol": "PENATA",
        "gol": "III/c",
        "tmt_pangkat": "01-04-2023",
        "jabatan": "ANALIS SUMBER DAYA MANUSIA APARATUR AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-05-2025",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - MANAJEMEN",
        "tahun_lulus": "2007",
        "jenjang": "SARJANA",
        "usia": "42 THN 2 BLN",
        "masa_kerja": "11 THN 7 BLN"
    },
    {
        "no": 69,
        "nama": "YULIA FITRI S.Kom.",
        "nip_raw": "19870615 201503 2 002",
        "ttl": "PADANG, 15-06-1987",
        "pangkat_gol": "PENATA",
        "gol": "III/c",
        "tmt_pangkat": "01-04-2023",
        "jabatan": "PRANATA KOMPUTER AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "02-09-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - SISTEM INFORMASI",
        "tahun_lulus": "2009",
        "jenjang": "SARJANA",
        "usia": "39 THN 3 BLN",
        "masa_kerja": "11 THN 6 BLN"
    },
    {
        "no": 70,
        "nama": "FIRZA HANGGARA S. Kom",
        "nip_raw": "19850627 201101 1 006",
        "ttl": "JAKARTA, 27-06-1985",
        "pangkat_gol": "PENATA",
        "gol": "III/c",
        "tmt_pangkat": "01-04-2024",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "22-12-2025",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - SISTEM INFORMASI",
        "tahun_lulus": "2014",
        "jenjang": "SARJANA",
        "usia": "41 THN 3 BLN",
        "masa_kerja": "13 THN 8 BLN"
    },
    {
        "no": 71,
        "nama": "MUHAMMAD SABIEL ADI PRAKASA S.ST., M.Ec.Dev.",
        "nip_raw": "19940914 201701 1 001",
        "ttl": "BANDAR LAMPUNG, 14-09-1994",
        "pangkat_gol": "PENATA",
        "gol": "III/c",
        "tmt_pangkat": "01-12-2025",
        "jabatan": "STATISTISI AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "12-06-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MAGISTER EKONOMI PEMBANGUNAN",
        "tahun_lulus": "2023",
        "jenjang": "PASCA SARJANA",
        "usia": "32 THN 0 BLN",
        "masa_kerja": "9 THN 8 BLN"
    },
    {
        "no": 72,
        "nama": "RIZKI WINANDA , S.E., M.E.",
        "nip_raw": "19900608 201503 1 004",
        "ttl": "BANDAR LAMPUNG, 08-06-1990",
        "pangkat_gol": "PENATA",
        "gol": "III/c",
        "tmt_pangkat": "01-03-2026",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "13-01-2026",
        "diklat": "PRAJABATAN CPNS GOL III",
        "tgl_diklat": "25-01-2016",
        "jam_diklat": "263",
        "pendidikan": "PASCA SARJANA - ILMU EKONOMI",
        "tahun_lulus": "2020",
        "jenjang": "PASCA SARJANA",
        "usia": "36 THN 3 BLN",
        "masa_kerja": "11 THN 6 BLN"
    },
    {
        "no": 73,
        "nama": "GLADYTHA GUNAWAN S.STP. M.Si.",
        "nip_raw": "19940127 201507 2 001",
        "ttl": "BANDAR LAMPUNG, 27-01-1994",
        "pangkat_gol": "PENATA",
        "gol": "III/c",
        "tmt_pangkat": "01-03-2026",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "13-01-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - ILMU ADMINSTRASI",
        "tahun_lulus": "2017",
        "jenjang": "PASCA SARJANA",
        "usia": "32 THN 8 BLN",
        "masa_kerja": "11 THN 2 BLN"
    },
    {
        "no": 74,
        "nama": "NAFIAH PRATIWI S.IP",
        "nip_raw": "19840409 201001 2 019",
        "ttl": "TEGAL, 09-04-1984",
        "pangkat_gol": "PENATA",
        "gol": "III/c",
        "tmt_pangkat": "01-04-2026",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-05-2025",
        "diklat": "PRAJABATAN GOLONGAN II",
        "tgl_diklat": "28-03-2011",
        "jam_diklat": "90",
        "pendidikan": "SARJANA - ILMU PEMERINTAHAN",
        "tahun_lulus": "2024",
        "jenjang": "SARJANA",
        "usia": "42 THN 5 BLN",
        "masa_kerja": "14 THN 8 BLN"
    },
    {
        "no": 75,
        "nama": "RIA PRIMADEKA SE",
        "nip_raw": "19850806 201001 2 018",
        "ttl": "TANJUNG KARANG, 06-08-1985",
        "pangkat_gol": "PENATA MUDA TK. I",
        "gol": "III/b",
        "tmt_pangkat": "01-10-2019",
        "jabatan": "PERENCANA AHLI PERTAMA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "18-10-2022",
        "diklat": "PRAJAB GOL II",
        "tgl_diklat": "06-05-2011",
        "jam_diklat": "90",
        "pendidikan": "SARJANA - EKONOMI AKUNTANSI",
        "tahun_lulus": "2014",
        "jenjang": "SARJANA",
        "usia": "41 THN 1 BLN",
        "masa_kerja": "14 THN 8 BLN"
    },
    {
        "no": 76,
        "nama": "KARTINI S.H",
        "nip_raw": "19730430 200701 2 007",
        "ttl": "LAMPUNG UTARA, 30-04-1973",
        "pangkat_gol": "PENATA MUDA TK. I",
        "gol": "III/b",
        "tmt_pangkat": "01-04-2021",
        "jabatan": "PERENCANA AHLI MUDA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "02-09-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - HUKUM",
        "tahun_lulus": "2005",
        "jenjang": "SARJANA",
        "usia": "53 THN 5 BLN",
        "masa_kerja": "22 THN 5 BLN"
    },
    {
        "no": 77,
        "nama": "BAMBANG ERY SUGIHONO",
        "nip_raw": "19680917 199303 1 003",
        "ttl": "BANDAR LAMPUNG, 17-09-1968",
        "pangkat_gol": "PENATA MUDA TK. I",
        "gol": "III/b",
        "tmt_pangkat": "01-10-2021",
        "jabatan": "PENGADMINISTRASI PERKANTORAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SLTA UMUM - SEKOLAH MENENGAH ATAS",
        "tahun_lulus": "2000",
        "jenjang": "SLTA UMUM",
        "usia": "58 THN 0 BLN",
        "masa_kerja": "25 THN 6 BLN"
    },
    {
        "no": 78,
        "nama": "BERTHA MIRZALIA DJUNAIDI S. Kom., M.M",
        "nip_raw": "19811025 201001 2 002",
        "ttl": "TANJUNG KARANG, 25-10-1981",
        "pangkat_gol": "PENATA MUDA TK. I",
        "gol": "III/b",
        "tmt_pangkat": "01-04-2022",
        "jabatan": "PERENCANA AHLI PERTAMA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "PASCA SARJANA - MANAJEMEN",
        "tahun_lulus": "2024",
        "jenjang": "PASCA SARJANA",
        "usia": "44 THN 11 BLN",
        "masa_kerja": "16 THN 8 BLN"
    },
    {
        "no": 79,
        "nama": "MALIK SYARIFUDIN S.IP.",
        "nip_raw": "19690508 200701 1 014",
        "ttl": "PALEMBANG, 08-05-1969",
        "pangkat_gol": "PENATA MUDA TK. I",
        "gol": "III/b",
        "tmt_pangkat": "01-10-2022",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - ILMU PEMERINTAHAN",
        "tahun_lulus": "2017",
        "jenjang": "SARJANA",
        "usia": "57 THN 4 BLN",
        "masa_kerja": "24 THN 11 BLN"
    },
    {
        "no": 80,
        "nama": "BELLA RAYENDRA HIPPY S.K.M.,M.M",
        "nip_raw": "19920211 201503 2 002",
        "ttl": "TANJUNG KARANG, 11-02-1992",
        "pangkat_gol": "PENATA MUDA TK. I",
        "gol": "III/b",
        "tmt_pangkat": "01-04-2023",
        "jabatan": "PERENCANA AHLI PERTAMA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "27-06-2023",
        "diklat": "PRAJAB",
        "tgl_diklat": "23-04-2016",
        "jam_diklat": "274",
        "pendidikan": "PASCA SARJANA - MANAJEMEN",
        "tahun_lulus": "2024",
        "jenjang": "PASCA SARJANA",
        "usia": "34 THN 7 BLN",
        "masa_kerja": "9 THN 7 BLN"
    },
    {
        "no": 81,
        "nama": "INTAN SARI AMSYA A.Md.",
        "nip_raw": "19810915 201001 2 010",
        "ttl": "TANJUNG KARANG, 15-09-1981",
        "pangkat_gol": "PENATA MUDA TK. I",
        "gol": "III/b",
        "tmt_pangkat": "01-10-2023",
        "jabatan": "PENGOLAH DATA DAN INFORMASI PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "DIPLOMA III - HUBUNGAN MASYARAKAT",
        "tahun_lulus": "2002",
        "jenjang": "DIPLOMA III",
        "usia": "45 THN 0 BLN",
        "masa_kerja": "15 THN 5 BLN"
    },
    {
        "no": 82,
        "nama": "ANDRE NUGRAHA PUTRA S.Tr.IP",
        "nip_raw": "19980921 202108 1 002",
        "ttl": "BANDAR LAMPUNG, 21-09-1999",
        "pangkat_gol": "PENATA MUDA TK. I",
        "gol": "III/b",
        "tmt_pangkat": "01-01-2025",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "21-01-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "DIPLOMA IV - KEUANGAN DAERAH",
        "tahun_lulus": "2021",
        "jenjang": "DIPLOMA IV",
        "usia": "27 THN 0 BLN",
        "masa_kerja": "5 THN 1 BLN"
    },
    {
        "no": 83,
        "nama": "RITA MUSTIKA SARI S.Si",
        "nip_raw": "19920613 201902 2 005",
        "ttl": "LAMPUNG TIMUR, 13-06-1992",
        "pangkat_gol": "PENATA MUDA TK. I",
        "gol": "III/b",
        "tmt_pangkat": "01-12-2025",
        "jabatan": "PERENCANA AHLI PERTAMA PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "14-06-2022",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - STATISTIK",
        "tahun_lulus": "2014",
        "jenjang": "SARJANA",
        "usia": "34 THN 3 BLN",
        "masa_kerja": "7 THN 7 BLN"
    },
    {
        "no": 84,
        "nama": "NIA WULAN SARI",
        "nip_raw": "19780628 200701 2 015",
        "ttl": "TANJUNGKARANG, 28-06-1978",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-04-2023",
        "jabatan": "PENGADMINISTRASI PERKANTORAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SEKOLAH TEKNIK MENENGAH",
        "tahun_lulus": "1997",
        "jenjang": "SLTA KEJURUAN",
        "usia": "48 THN 3 BLN",
        "masa_kerja": "28 THN 5 BLN"
    },
    {
        "no": 85,
        "nama": "AKHMAD RODI",
        "nip_raw": "19740705 200701 1 015",
        "ttl": "NEGERI SAKTI, 05-07-1974",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-04-2023",
        "jabatan": "PENGADMINISTRASI PERKANTORAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "21-01-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SLTA UMUM - A.3/IPS",
        "tahun_lulus": "1997",
        "jenjang": "SLTA UMUM",
        "usia": "52 THN 2 BLN",
        "masa_kerja": "28 THN 5 BLN"
    },
    {
        "no": 86,
        "nama": "M. FAREZA AKBAR S.Tr.I.P",
        "nip_raw": "20020827 202409 1 001",
        "ttl": "BANDAR LAMPUNG, 27-08-2002",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-09-2024",
        "jabatan": "FASILITATOR PEMERINTAHAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH",
        "tmt_jabatan": "01-01-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "DIPLOMA IV - PRAKTIK PERPOLISIAN TATA PAMONG",
        "tahun_lulus": "2024",
        "jenjang": "DIPLOMA IV",
        "usia": "24 THN 1 BLN",
        "masa_kerja": "1 THN 6 BLN"
    },
    {
        "no": 87,
        "nama": "SARAH NABILA PUTRI S.Tr.I.P.",
        "nip_raw": "20020902 202409 2 001",
        "ttl": "MUARA ENIM, 02-09-2002",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-09-2024",
        "jabatan": "FASILITATOR PEMERINTAHAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH",
        "tmt_jabatan": "01-01-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "DIPLOMA IV - MANAJEMEN SUMBER DAYA MANUSIA SEKTOR PUBLIK",
        "tahun_lulus": "2024",
        "jenjang": "DIPLOMA IV",
        "usia": "24 THN 0 BLN",
        "masa_kerja": "1 THN 6 BLN"
    },
    {
        "no": 88,
        "nama": "SATRIA DESTRIAN MAHCMUDDIN S.Kom",
        "nip_raw": "19921222 202504 1 004",
        "ttl": "LAMPUNG TENGAH, 22-12-1992",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-04-2025",
        "jabatan": "PENATA KELOLA SISTEM DAN TEKNOLOGI INFORMASI PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "01-04-2025",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - INFORMATIKA",
        "tahun_lulus": "2017",
        "jenjang": "SARJANA",
        "usia": "33 THN 9 BLN",
        "masa_kerja": "1 THN 5 BLN"
    },
    {
        "no": 89,
        "nama": "NOVIA TRIANI PUTRI ST",
        "nip_raw": "19951108 202504 2 004",
        "ttl": "BANDAR LAMPUNG, 08-11-1995",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-04-2025",
        "jabatan": "PENATA KELOLA SISTEM DAN TEKNOLOGI INFORMASI PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "01-04-2025",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - TEKNIK INFORMATIKA",
        "tahun_lulus": "2018",
        "jenjang": "SARJANA",
        "usia": "30 THN 10 BLN",
        "masa_kerja": "1 THN 5 BLN"
    },
    {
        "no": 90,
        "nama": "M.GERRY ZADA ALEM S.I.P.",
        "nip_raw": "19960309 202504 1 003",
        "ttl": "BANDAR LAMPUNG, 09-03-1996",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-04-2025",
        "jabatan": "PENATA KELOLA PEMERINTAHAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "01-04-2025",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - ILMU PEMERINTAHAN",
        "tahun_lulus": "2019",
        "jenjang": "SARJANA",
        "usia": "30 THN 6 BLN",
        "masa_kerja": "1 THN 5 BLN"
    },
    {
        "no": 91,
        "nama": "RIZAL ANDIKA SAPUTRA S.Kom",
        "nip_raw": "19970520 202504 1 006",
        "ttl": "LAMPUNG SELATAN, 20-05-1997",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-04-2025",
        "jabatan": "PENATA KELOLA SISTEM DAN TEKNOLOGI INFORMASI PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "01-04-2025",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - INFORMATIKA",
        "tahun_lulus": "2019",
        "jenjang": "SARJANA",
        "usia": "29 THN 4 BLN",
        "masa_kerja": "1 THN 5 BLN"
    },
    {
        "no": 92,
        "nama": "NASARUDDIN",
        "nip_raw": "19740212 200903 1 002",
        "ttl": "PADANGRATU, 12-02-1974",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-11-2025",
        "jabatan": "PENGADMINISTRASI PERKANTORAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "21-01-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SLTA UMUM - SEKOLAH MENENGAH ATAS",
        "tahun_lulus": "1994",
        "jenjang": "SLTA UMUM",
        "usia": "52 THN 7 BLN",
        "masa_kerja": "21 THN 8 BLN"
    },
    {
        "no": 93,
        "nama": "HALIJATUS SAKDIYAH S.M.",
        "nip_raw": "19800509 201001 2 003",
        "ttl": "NEGERI KATON, 09-05-1980",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-12-2025",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "21-01-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - MANAJEMEN",
        "tahun_lulus": "2005",
        "jenjang": "SARJANA",
        "usia": "46 THN 4 BLN",
        "masa_kerja": "22 THN 8 BLN"
    },
    {
        "no": 94,
        "nama": "BURHAN S.IP.",
        "nip_raw": "19720609 200701 1 025",
        "ttl": "MUARA DUA OKU, 09-06-1972",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-03-2026",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "28-04-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - ILMU PEMERINTAHAN",
        "tahun_lulus": "2023",
        "jenjang": "SARJANA",
        "usia": "54 THN 3 BLN",
        "masa_kerja": "23 THN 11 BLN"
    },
    {
        "no": 95,
        "nama": "SUGIMAN S.A.P.",
        "nip_raw": "19720809 200701 1 020",
        "ttl": "CAMPUR ASRI, 09-08-1972",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-03-2026",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "28-04-2026",
        "diklat": "DIKLAT PRAJABAT GOLONGAN SATU",
        "tgl_diklat": "01-04-2009",
        "jam_diklat": "174",
        "pendidikan": "SARJANA - ADMINISTRASI PUBLIK",
        "tahun_lulus": "2025",
        "jenjang": "SARJANA",
        "usia": "54 THN 1 BLN",
        "masa_kerja": "19 THN 5 BLN"
    },
    {
        "no": 96,
        "nama": "LANGGENG BASUKI S.A.P.",
        "nip_raw": "19840101 201212 1 003",
        "ttl": "LAMPUNG TIMUR, 01-01-1984",
        "pangkat_gol": "PENATA MUDA",
        "gol": "III/a",
        "tmt_pangkat": "01-04-2026",
        "jabatan": "PENELAAH TEKNIS KEBIJAKAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "28-04-2026",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SARJANA - ADMINISTRASI PUBLIK",
        "tahun_lulus": "2023",
        "jenjang": "SARJANA",
        "usia": "42 THN 8 BLN",
        "masa_kerja": "21 THN 8 BLN"
    },
    {
        "no": 97,
        "nama": "ICHSAN RIZKI SETIAWAN A.Md.",
        "nip_raw": "19790326 200604 1 004",
        "ttl": "KOTABUMI, 26-03-1979",
        "pangkat_gol": "PENGATUR TK. I",
        "gol": "II/d",
        "tmt_pangkat": "01-04-2022",
        "jabatan": "PENGOLAH DATA DAN INFORMASI PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "DIPLOMA III - KOMUNIKASI",
        "tahun_lulus": "2004",
        "jenjang": "DIPLOMA III",
        "usia": "47 THN 6 BLN",
        "masa_kerja": "23 THN 5 BLN"
    },
    {
        "no": 98,
        "nama": "JAUHARI",
        "nip_raw": "19700123 200701 1 006",
        "ttl": "NEGERI AGUNG, 23-01-1970",
        "pangkat_gol": "PENGATUR",
        "gol": "II/c",
        "tmt_pangkat": "01-10-2022",
        "jabatan": "PENGADMINISTRASI PERKANTORAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SLTA UMUM - SLTA UMUM",
        "tahun_lulus": "2012",
        "jenjang": "SLTA UMUM",
        "usia": "56 THN 8 BLN",
        "masa_kerja": "23 THN 11 BLN"
    },
    {
        "no": 99,
        "nama": "SUHERMAN",
        "nip_raw": "19791204 200701 1 003",
        "ttl": "TELUKBETUNG, 04-12-1979",
        "pangkat_gol": "PENGATUR",
        "gol": "II/c",
        "tmt_pangkat": "01-10-2023",
        "jabatan": "PENGADMINISTRASI PERKANTORAN PADA BADAN PERENCANAAN PEMBANGUNAN DAERAH PROVINSI LAMPUNG",
        "tmt_jabatan": "31-12-2024",
        "diklat": "-",
        "tgl_diklat": "-",
        "jam_diklat": "-",
        "pendidikan": "SLTA UMUM - SEKOLAH MENENGAH ATAS",
        "tahun_lulus": "2009",
        "jenjang": "SLTA UMUM",
        "usia": "46 THN 9 BLN",
        "masa_kerja": "21 THN 5 BLN"
    }
]

print(f"Total ASN extracted: {len(raw_duk)}")
with open('duk_2026_raw.json', 'w', encoding='utf-8') as f:
    json.dump(raw_duk, f, indent=2, ensure_ascii=False)
