-- ===========================================================================
-- SIP-KOMPETENSI: SETUP SUPABASE REALTIME NOTIFIKASI (TAHAP 5.3)
-- ===========================================================================

-- 1. Buat tabel notifikasi
create table if not exists notifikasi (
    id bigint generated by default as identity primary key,
    penerima text,
    pengirim text,
    judul text,
    pesan text,
    tipe text default 'info',
    dibaca boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. Matikan RLS untuk tabel notifikasi internal kedinasan
alter table notifikasi disable row level security;

-- 3. Tambahkan ke publikasi Supabase Realtime agar setiap insert memicu event broadcast
alter publication supabase_realtime add table notifikasi;
